#!/usr/bin/env sh
if [ -z "$(docker network ls --filter name=^ch-tab$ --format={{.Name}})" ]; then
  echo "Creating ch-tab Docker network"
  docker network create ch-tab
fi

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

show_help() {
  echo "
    Usage: path/to/ch-tab-core [OPTION...]
    Run services.

    Options:
      -h, --help               display this help text
    "
}

while :; do
  case $1 in    
    -h|--help)   # Call a "show_help" function to display a synopsis, then exit.
      show_help
      exit
      ;;
    *)
      break
  esac

  shift
done

cd "${projectRoot}"

  ./ch-tab-api/scripts/start -d;